### ISSUE TITLE
Services/Applications marked as protocols

### ISSUE THREAD

**Issue by pcbaldwin** [eglooca/netify-daemon#1]
It looks like nDPI will mark some "service" traffic as a "protocol".  For example, I noticed the following flow data:

```
+-------+-------------------+------------------------+-----------------+
| id    | detected_protocol | detected_protocol_name | other_ip        |
+-------+-------------------+------------------------+-----------------+
|  4252 |               126 | Google                 | 173.194.198.188 |
|  4255 |               126 | Google                 | 173.194.198.188 |
|  7510 |               126 | Google                 | 173.194.68.156  |
```

I'm never expecting the 126/NDPI_SERVICE_GOOGLE as a "detected_protocol" in a flow... it's not a protocol!  Doing some digging, it looks like all the nDPI network matching is treated as a protocol, i.e. in ndpi_content_match.c.inc, I see this network match defined:

```
{ 0xADC20000 /* 173.194.0.0 */, 16, NDPI_SERVICE_GOOGLE },
{ 0x40E91600 /* 64.233.160.0 */, 19, NDPI_SERVICE_GOOGLE },
```

... which jives with the "other_ips" listed in the above flow table output.  In the same source file, I also see:

```
{ ".google.",         "Google",   NDPI_SERVICE_GOOGLE, NDPI_PROTOCOL_ACCEPTABLE },
{ ".gstatic.com",     "Google",   NDPI_SERVICE_GOOGLE, NDPI_PROTOCOL_ACCEPTABLE },
  ... etc ...
```

So this same 126/NDPI_SERVICE_GOOGLE constant ends up as a "detected_service" in the flow data (as expected).

**Comment by pcbaldwin** [comment]
As discussed, the main culprits are found **ndpi_content_match.c.inc**, but I noticed a similar problem in the Twitter "protocol" **/src/lib/protocols/twitter.c**

**Comment by dsokoloski** [comment]
I have fixed the twitter.c issue.  It was reversed in there for some reason, along with one other obscure protocol.

The ndpi_content_match.c.inc issues will be resolved by us not including it at all.  We will pull content from there that we want to keep, storing that in a database.  The daemon will pull that configuration and load it dynamically.  That way we have total control over the content of that include.

I will close this issue when that has been completed.

**Comment by dsokoloski** [comment]
Latest build now loads content-match data from two external CSV files.  When netify-sink is enabled, those configuration files can now be updated from the portal.  We can now fix any cases where service IDs are being used as protocol IDs.
